Repository PlasticSCM/UEPlasticPlugin, pull requests merged in 2023-03, with the labels that each got.

#70 Add support for Unreal 5 "soft revert" to undockeckout without reverting the file content
  Source/PlasticSourceControl/Private/PlasticSourceControlOperations.cpp
  Source/PlasticSourceControl/Private/PlasticSourceControlState.h
  Source/PlasticSourceControl/Private/PlasticSourceControlVersions.h
Labels: enhancement, ue5

#69 Improve performances of "move" operations by calling status with --controlledchanged instead of --all
  Source/PlasticSourceControl/Private/PlasticSourceControlOperations.cpp
  Source/PlasticSourceControl/Private/PlasticSourceControlUtils.cpp
  Source/PlasticSourceControl/Private/PlasticSourceControlUtils.h
Labels: performances

#73 Detect asset checked-out but unchanged
  Source/PlasticSourceControl/Private/PlasticSourceControlOperations.cpp
  Source/PlasticSourceControl/Private/PlasticSourceControlProvider.cpp
  Source/PlasticSourceControl/Private/PlasticSourceControlProvider.h
  Source/PlasticSourceControl/Private/PlasticSourceControlState.cpp
  Source/PlasticSourceControl/Private/PlasticSourceControlState.h
  Source/PlasticSourceControl/Private/PlasticSourceControlUtils.cpp
  Source/PlasticSourceControl/Private/PlasticSourceControlVersions.h
Labels: enhancement
